# Use Ubuntu 16.04 as the base image
FROM ubuntu:16.04

# Install dependencies and tools
RUN apt-get update && apt-get install -y \
    autoconf \
    bzip2 \
    g++-mingw-w64-i686 \
    gcc-mingw-w64-i686 \
    gettext \
    libtool \
    make \
    pkg-config && \
    apt-get clean

# Set the working directory
WORKDIR /vlc-build

# Copy the vlc-2.2.8 source code
COPY vlc-2.2.8 ./

# Prepare the 3rd party libraries
RUN cd contrib/win32 && \
    ../bootstrap --host=i686-w64-mingw32 && \
    make prebuilt

# Configure VLC for Windows 32-bit compilation
RUN ./bootstrap && \
    mkdir win32 && cd win32 && \
    ../extras/package/win32/configure.sh --host=i686-w64-mingw32 --build=x86_64-pc-linux-gnu

# Build VLC
RUN cd win32 && \
    make package-win-common

# Set the default command
CMD ["bash"]
